/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtable;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author JEANNE
 */
public class GpDiary extends javax.swing.JFrame {

    /**
     * Creates new form appointmentDiary
     */
    public GpDiary() {
        initComponents();
        GpDiaryTable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){
        
    @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {

        JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        l.setBorder(new LineBorder(Color.BLACK, 1));
        l.setBackground(new Color(165, 205, 255));
        l.setForeground(Color.WHITE);
        l.setHorizontalAlignment(JLabel.CENTER);
      
        return l;
        }
    });
    
        GpDiaryTable.getTableHeader().setPreferredSize(new Dimension(32, 32));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GpDiaryContentPanel = new javax.swing.JPanel();
        GpDiaryTablePanel = new javax.swing.JPanel();
        GpDiaryScrollPane = new javax.swing.JScrollPane();
        GpDiaryTable = new javax.swing.JTable();
        GpDiaryTitlePanel = new javax.swing.JPanel();
        GpDiaryTitleLabel = new javax.swing.JLabel();
        GpDiaryButtonPanel = new javax.swing.JPanel();
        GpDiaryBackButton = new javax.swing.JButton();
        GpDiaryExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GpDiaryContentPanel.setBackground(new java.awt.Color(204, 204, 204));
        GpDiaryContentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        GpDiaryTablePanel.setBackground(new java.awt.Color(165, 205, 255));
        GpDiaryTablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.SystemColor.textHighlight, java.awt.SystemColor.textHighlight, null, null));

        GpDiaryTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GpDiaryTable.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        GpDiaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Time", "Patient Name"
            }
        ));
        GpDiaryTable.setGridColor(new java.awt.Color(0, 0, 0));
        GpDiaryTable.setRowHeight(20);
        GpDiaryTable.setSelectionBackground(new java.awt.Color(255, 255, 204));
        GpDiaryTable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        GpDiaryTable.setShowGrid(true);
        GpDiaryScrollPane.setViewportView(GpDiaryTable);

        GpDiaryTitlePanel.setBackground(java.awt.SystemColor.textHighlight);

        GpDiaryTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        GpDiaryTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        GpDiaryTitleLabel.setText("GP Diary");

        javax.swing.GroupLayout GpDiaryTitlePanelLayout = new javax.swing.GroupLayout(GpDiaryTitlePanel);
        GpDiaryTitlePanel.setLayout(GpDiaryTitlePanelLayout);
        GpDiaryTitlePanelLayout.setHorizontalGroup(
            GpDiaryTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GpDiaryTitlePanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(GpDiaryTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GpDiaryTitlePanelLayout.setVerticalGroup(
            GpDiaryTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GpDiaryTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GpDiaryTablePanelLayout = new javax.swing.GroupLayout(GpDiaryTablePanel);
        GpDiaryTablePanel.setLayout(GpDiaryTablePanelLayout);
        GpDiaryTablePanelLayout.setHorizontalGroup(
            GpDiaryTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GpDiaryTablePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(GpDiaryTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GpDiaryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(GpDiaryTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        GpDiaryTablePanelLayout.setVerticalGroup(
            GpDiaryTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GpDiaryTablePanelLayout.createSequentialGroup()
                .addComponent(GpDiaryTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GpDiaryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        GpDiaryButtonPanel.setBackground(java.awt.SystemColor.textHighlight);
        GpDiaryButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.SystemColor.textHighlight, java.awt.SystemColor.textHighlight, null, null));

        GpDiaryBackButton.setBackground(java.awt.SystemColor.textHighlight);
        GpDiaryBackButton.setForeground(new java.awt.Color(255, 255, 255));
        GpDiaryBackButton.setText("Back");
        GpDiaryBackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.SystemColor.textHighlight, java.awt.SystemColor.textHighlight, null, null));

        GpDiaryExitButton.setBackground(java.awt.SystemColor.textHighlight);
        GpDiaryExitButton.setForeground(new java.awt.Color(255, 255, 255));
        GpDiaryExitButton.setText("Exit");
        GpDiaryExitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.SystemColor.textHighlight, java.awt.SystemColor.textHighlight, null, null));

        javax.swing.GroupLayout GpDiaryButtonPanelLayout = new javax.swing.GroupLayout(GpDiaryButtonPanel);
        GpDiaryButtonPanel.setLayout(GpDiaryButtonPanelLayout);
        GpDiaryButtonPanelLayout.setHorizontalGroup(
            GpDiaryButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GpDiaryButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GpDiaryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GpDiaryExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        GpDiaryButtonPanelLayout.setVerticalGroup(
            GpDiaryButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GpDiaryButtonPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(GpDiaryButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GpDiaryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GpDiaryExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout GpDiaryContentPanelLayout = new javax.swing.GroupLayout(GpDiaryContentPanel);
        GpDiaryContentPanel.setLayout(GpDiaryContentPanelLayout);
        GpDiaryContentPanelLayout.setHorizontalGroup(
            GpDiaryContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GpDiaryContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GpDiaryContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GpDiaryTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GpDiaryButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GpDiaryContentPanelLayout.setVerticalGroup(
            GpDiaryContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GpDiaryContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GpDiaryTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GpDiaryButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GpDiaryContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GpDiaryContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GpDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GpDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GpDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GpDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GpDiary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GpDiaryBackButton;
    private javax.swing.JPanel GpDiaryButtonPanel;
    private javax.swing.JPanel GpDiaryContentPanel;
    private javax.swing.JButton GpDiaryExitButton;
    private javax.swing.JScrollPane GpDiaryScrollPane;
    private javax.swing.JTable GpDiaryTable;
    private javax.swing.JPanel GpDiaryTablePanel;
    private javax.swing.JLabel GpDiaryTitleLabel;
    private javax.swing.JPanel GpDiaryTitlePanel;
    // End of variables declaration//GEN-END:variables
}
